//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO_DMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCheckInDocumentsPath {
            get {
                return ((string)(this["LastCheckInDocumentsPath"]));
            }
            set {
                this["LastCheckInDocumentsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchISODocumentType {
            get {
                return ((string)(this["SearchISODocumentType"]));
            }
            set {
                this["SearchISODocumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchISOTierLevel {
            get {
                return ((string)(this["SearchISOTierLevel"]));
            }
            set {
                this["SearchISOTierLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchISOTitleContains {
            get {
                return ((string)(this["SearchISOTitleContains"]));
            }
            set {
                this["SearchISOTitleContains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchOfficeDocumentType {
            get {
                return ((string)(this["SearchOfficeDocumentType"]));
            }
            set {
                this["SearchOfficeDocumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchEffectiveDateStart {
            get {
                return ((string)(this["SearchEffectiveDateStart"]));
            }
            set {
                this["SearchEffectiveDateStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchEffectiveDateEnd {
            get {
                return ((string)(this["SearchEffectiveDateEnd"]));
            }
            set {
                this["SearchEffectiveDateEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchDateCreatedStart {
            get {
                return ((string)(this["SearchDateCreatedStart"]));
            }
            set {
                this["SearchDateCreatedStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchDateCreatedEnd {
            get {
                return ((string)(this["SearchDateCreatedEnd"]));
            }
            set {
                this["SearchDateCreatedEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchLastRevisionDateStart {
            get {
                return ((string)(this["SearchLastRevisionDateStart"]));
            }
            set {
                this["SearchLastRevisionDateStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchLastRevisionDateEnd {
            get {
                return ((string)(this["SearchLastRevisionDateEnd"]));
            }
            set {
                this["SearchLastRevisionDateEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchCreatedBy {
            get {
                return ((string)(this["SearchCreatedBy"]));
            }
            set {
                this["SearchCreatedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchRevisedBy {
            get {
                return ((string)(this["SearchRevisedBy"]));
            }
            set {
                this["SearchRevisedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxISODocumentType {
            get {
                return ((bool)(this["SearchCheckBoxISODocumentType"]));
            }
            set {
                this["SearchCheckBoxISODocumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxISOTierLevel {
            get {
                return ((bool)(this["SearchCheckBoxISOTierLevel"]));
            }
            set {
                this["SearchCheckBoxISOTierLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxISODocumentTitle {
            get {
                return ((bool)(this["SearchCheckBoxISODocumentTitle"]));
            }
            set {
                this["SearchCheckBoxISODocumentTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxOfficeDocumentType {
            get {
                return ((bool)(this["SearchCheckBoxOfficeDocumentType"]));
            }
            set {
                this["SearchCheckBoxOfficeDocumentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxEffectiveDate {
            get {
                return ((bool)(this["SearchCheckBoxEffectiveDate"]));
            }
            set {
                this["SearchCheckBoxEffectiveDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxDateCreated {
            get {
                return ((bool)(this["SearchCheckBoxDateCreated"]));
            }
            set {
                this["SearchCheckBoxDateCreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxLastRevisionDate {
            get {
                return ((bool)(this["SearchCheckBoxLastRevisionDate"]));
            }
            set {
                this["SearchCheckBoxLastRevisionDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxCreatedBy {
            get {
                return ((bool)(this["SearchCheckBoxCreatedBy"]));
            }
            set {
                this["SearchCheckBoxCreatedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxRevisedBy {
            get {
                return ((bool)(this["SearchCheckBoxRevisedBy"]));
            }
            set {
                this["SearchCheckBoxRevisedBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool documentSearchInProgress {
            get {
                return ((bool)(this["documentSearchInProgress"]));
            }
            set {
                this["documentSearchInProgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string documentSearchSQLText {
            get {
                return ((string)(this["documentSearchSQLText"]));
            }
            set {
                this["documentSearchSQLText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxDepartment {
            get {
                return ((bool)(this["SearchCheckBoxDepartment"]));
            }
            set {
                this["SearchCheckBoxDepartment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchDepartment {
            get {
                return ((string)(this["SearchDepartment"]));
            }
            set {
                this["SearchDepartment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentUserSecurityLevel {
            get {
                return ((int)(this["CurrentUserSecurityLevel"]));
            }
            set {
                this["CurrentUserSecurityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentUsername {
            get {
                return ((string)(this["CurrentUsername"]));
            }
            set {
                this["CurrentUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RevisonCheckedIn {
            get {
                return ((bool)(this["RevisonCheckedIn"]));
            }
            set {
                this["RevisonCheckedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideRevisions {
            get {
                return ((bool)(this["HideRevisions"]));
            }
            set {
                this["HideRevisions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool scanningCancelled {
            get {
                return ((bool)(this["scanningCancelled"]));
            }
            set {
                this["scanningCancelled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SOPJobCodeLookUp {
            get {
                return ((string)(this["SOPJobCodeLookUp"]));
            }
            set {
                this["SOPJobCodeLookUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowISODocumentsOnly {
            get {
                return ((bool)(this["ShowISODocumentsOnly"]));
            }
            set {
                this["ShowISODocumentsOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublishedVersion {
            get {
                return ((string)(this["PublishedVersion"]));
            }
            set {
                this["PublishedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridMargin {
            get {
                return ((string)(this["GridMargin"]));
            }
            set {
                this["GridMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridTop {
            get {
                return ((int)(this["GridTop"]));
            }
            set {
                this["GridTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridLeft {
            get {
                return ((int)(this["GridLeft"]));
            }
            set {
                this["GridLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GridHeight {
            get {
                return ((int)(this["GridHeight"]));
            }
            set {
                this["GridHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchCustomer {
            get {
                return ((string)(this["SearchCustomer"]));
            }
            set {
                this["SearchCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchProduct {
            get {
                return ((string)(this["SearchProduct"]));
            }
            set {
                this["SearchProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchUserDefinedCategories {
            get {
                return ((string)(this["SearchUserDefinedCategories"]));
            }
            set {
                this["SearchUserDefinedCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxUserDefinedCategories {
            get {
                return ((bool)(this["SearchCheckBoxUserDefinedCategories"]));
            }
            set {
                this["SearchCheckBoxUserDefinedCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxCustomer {
            get {
                return ((bool)(this["SearchCheckBoxCustomer"]));
            }
            set {
                this["SearchCheckBoxCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxProduct {
            get {
                return ((bool)(this["SearchCheckBoxProduct"]));
            }
            set {
                this["SearchCheckBoxProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchISOTag {
            get {
                return ((string)(this["SearchISOTag"]));
            }
            set {
                this["SearchISOTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxISOTag {
            get {
                return ((bool)(this["SearchCheckBoxISOTag"]));
            }
            set {
                this["SearchCheckBoxISOTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchVendor {
            get {
                return ((string)(this["SearchVendor"]));
            }
            set {
                this["SearchVendor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchCheckBoxVendor {
            get {
                return ((bool)(this["SearchCheckBoxVendor"]));
            }
            set {
                this["SearchCheckBoxVendor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchShowAllUserDefinedCategories {
            get {
                return ((bool)(this["SearchShowAllUserDefinedCategories"]));
            }
            set {
                this["SearchShowAllUserDefinedCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModifyDocumentsShowAllUserDefinedCategories {
            get {
                return ((bool)(this["ModifyDocumentsShowAllUserDefinedCategories"]));
            }
            set {
                this["ModifyDocumentsShowAllUserDefinedCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContinuousScanning {
            get {
                return ((bool)(this["ContinuousScanning"]));
            }
            set {
                this["ContinuousScanning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string monitoredDocumentName {
            get {
                return ((string)(this["monitoredDocumentName"]));
            }
            set {
                this["monitoredDocumentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cancelRefreshMasterDocuments {
            get {
                return ((bool)(this["cancelRefreshMasterDocuments"]));
            }
            set {
                this["cancelRefreshMasterDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool documentCountUpdatedByCurrentUser {
            get {
                return ((bool)(this["documentCountUpdatedByCurrentUser"]));
            }
            set {
                this["documentCountUpdatedByCurrentUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RevistedDocumentPath {
            get {
                return ((string)(this["RevistedDocumentPath"]));
            }
            set {
                this["RevistedDocumentPath"] = value;
            }
        }
    }
}
